# Lektor Configuration File
# Copy this to ~/.config/lektor/config.toml and customize

[editor]
tab_width = 4
use_spaces = true
auto_indent = true
show_line_numbers = true
highlight_current_line = true
word_wrap = false
auto_save = false
auto_save_interval = 30
rainbow_brackets = true
highlight_matching_bracket = true
show_column_ruler = true
column_ruler_positions = [80, 100, 120]
show_whitespace = false
show_indent_guides = true

[theme]
name = "Dark"
syntax_theme = "Solarized (dark)"

[keybindings]
save = "Ctrl+S"
quit = "Ctrl+Q"
open = "Ctrl+O"
find = "Ctrl+F"
replace = "Ctrl+H"
goto_line = "Ctrl+G"
toggle_sidebar = "Ctrl+B"

[sidebar]
show_hidden_files = false
show_git_status = true
# Width of the sidebar in characters (default: 25)
width = 25

[session]
auto_save = true
auto_restore = true
workspace_sessions = true
restore_cursor_position = true
restore_open_buffers = true
