#!/bin/bash

echo "Testing Lektor sidebar functionality..."
echo ""
echo "1. Testing with current directory:"
echo "./target/release/lektor"
echo ""
echo "2. Testing with specific directory:"
echo "./target/release/lektor src/"
echo ""
echo "3. Testing with specific file:"
echo "./target/release/lektor src/main.rs"
echo ""
echo "Key bindings for sidebar:"
echo "- Ctrl+B: Toggle sidebar visibility"
echo "- Arrow keys: Navigate in sidebar (when focused)"
echo "- Enter: Open file/expand directory in sidebar"
echo ""
echo "Run any of the above commands to test the sidebar."
