#!/bin/bash
echo "Building Lektor..."
cargo build --release
echo "Build complete!"
echo ""
echo "To run Lektor:"
echo "  ./target/release/lektor [file]"
echo ""
echo "Key bindings:"
echo "  Normal mode:"
echo "    i - Insert mode"
echo "    : - Command mode"
echo "    Ctrl+B - Toggle sidebar"
echo "    Ctrl+S - Save"
echo "    Ctrl+Q - Quit"
echo "  Insert mode:"
echo "    Esc - Back to normal"
echo "  Command mode:"
echo "    :w - Save"
echo "    :q - Quit"
echo "    :wq - Save and quit"
